name: coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  scan:
    runs-on: ubuntu-22.04

    container:
      image: joinframework/join-ci:latest
      options: --privileged --sysctl net.ipv6.conf.all.disable_ipv6=0

    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.0

    - name: Configure
      run: cmake -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -DDCONV_ENABLE_COVERAGE=ON -DDCONV_ENABLE_TESTS=ON

    - name: Build
      run: cmake --build build --config Debug

    - name: Run tests
      run: ctest --test-dir build --output-on-failure -C Debug

    - name: Generate coverage report
      run: |
        lcov --directory build --capture --exclude "*/usr/include/*" --exclude '*/tests/*' --output-file lcov.info
        genhtml lcov.info --prefix $GITHUB_WORKSPACE --output-directory coverage

    - name: Upload coverage data to GitHub
      if: ${{ inputs.coverage }}
      uses: actions/upload-artifact@v4
      with:
        name: coverage-data
        path: lcov.info

    - name: Upload coverage report to coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        file: lcov.info

    - name: Upload coverage report to codecov
      uses: codecov/codecov-action@v3.1.1
      with:
        fail_ci_if_error: true
        token: ${{secrets.CODECOV_TOKEN}}
        flags: unittests
        file: lcov.info

    - name: Upload coverage report to codacy
      uses: codacy/codacy-coverage-reporter-action@v1.3.0
      with:
        project-token: ${{secrets.CODACY_PROJECT_TOKEN}}
        coverage-reports: lcov.info
